In [ ]:
# Q1_0112. arr에서 배열 [14, 21, 30]을 출력하세요.
arr[[3,5,7],[2,1,2]]

array([14, 21, 30])

In [ ]:
# Q2_0112. a 배열에 대해서 3차원 자리에 2차원을, 2차원 자리에 1차원을, 1차원 자리에 3차원을 넣어서 변환하세요.
a = np.arange(6).reshape(1,2,3)
print(np.transpose(a,(1,2,0)))

[[[0 3]]

 [[1 4]]

 [[2 5]]]
==================================================
[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]]

In [ ]:
# Q3_0112. 아래 배열에서 3차원과 2차원을 변경하여 출력하세요. (shape 확인)
arr = np.arange(24).reshape(2,3,4)
q3_arr = np.swapaxes(arr, 0,1)
print(q3_arr, q3_arr.shape)

[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]] (3, 2, 4)

In [ ]:
# Q4_0112. arr의 모든 양수를 2로 바꿀 경우를 출력하세요. (음수는 변경없음)
arr = np.random.randn(4,4)
print(arr)
print("="*50)
print(np.where(arr > 0, 2, arr))

[[ 0.66224629  1.73168155 -0.53254537 -0.86263886]
 [-0.76826562  1.92863055  1.09171612  0.89360313]
 [-0.98535974 -2.32116084 -0.58971651 -2.97467971]
 [ 1.28919101  0.32637963  0.11285013  2.38188886]]
==================================================
[[ 2.          2.         -0.53254537 -0.86263886]
 [-0.76826562  2.          2.          2.        ]
 [-0.98535974 -2.32116084 -0.58971651 -2.97467971]
 [ 2.          2.          2.          2.        ]]

In [ ]:
# Q5_0112. arr=np.random.randn(6)에 대해서 arr.sort를 행, 열축으로 정렬하세요
arr=np.random.randn(6).reshape(2,3)
ori=arr.copy()
print(arr, "\n"+"="*50)
arr.sort(axis=0)
print(arr, "\n"+"="*50)
ori.sort(axis=1)
print(ori)

[[-0.16256099  0.11688488 -0.32574886]
 [-0.46216344 -2.32695501  0.15717992]]
==================================================
[[-0.46216344 -2.32695501 -0.32574886]
 [-0.16256099  0.11688488  0.15717992]]
==================================================
[[-0.32574886 -0.16256099  0.11688488]
 [-2.32695501 -0.46216344  0.15717992]]

In [ ]:
# Q6_0112. 다음 배열에서 5% 분위수에 해당하는 요소값을 출력.
arr=np.random.randn(1000)
ans6 = arr[arr <= np.percentile(arr, 5)]
print(ans6)

[-2.20069437 -2.11443621 -1.77281391 -3.32416798 -2.68454026 -2.66697591
 -2.32800217 -2.16504473 -2.08362245 -2.34722577 -2.32036721 -1.81707021
 -1.94109397 -1.87939826 -2.15725485 -2.07605428 -1.73059105 -2.5001275
 -2.02908097 -1.99040515 -1.71603151 -2.46015478 -2.52531243 -2.13172016
 -1.80585842 -2.77863924 -1.92300374 -1.99575713 -2.28856817 -2.53978502
 -1.74928419 -2.3000281  -1.75016891 -1.71922508 -2.42845846 -2.2680313
 -2.26683297 -1.82093934 -1.77309662 -2.30544118 -2.0815724  -3.92370075
 -3.01149032 -1.6894662  -2.40161902 -1.70879436 -2.17349853 -1.8603365
 -1.78313617 -1.71590017]

In [ ]:
ar2d = np.arange(1,101).reshape(10,10)

# Q7_0112. ar2d 에서 50보다 큰 값 출력
ans7 = ar2d[ar2d > 50]
print(ans7)

[ 51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68
  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86
  87  88  89  90  91  92  93  94  95  96  97  98  99 100]

In [ ]:
# Q8_0112. np.ones((10,10))을 아래와 같이 출력
# array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])
q8 = np.ones((10,10))
q8[1:-1,1:-1] = 0
print(q8)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

In [ ]:
# Q9_0112. np.zeros((8,8))을 이용해서 아래와 같이 출력하세요. (두가지: 인덱싱, tile)
# array([[0, 1, 0, 1, 0, 1, 0, 1],
#        [1, 0, 1, 0, 1, 0, 1, 0],
#        [0, 1, 0, 1, 0, 1, 0, 1],
#        [1, 0, 1, 0, 1, 0, 1, 0],
#        [0, 1, 0, 1, 0, 1, 0, 1],
#        [1, 0, 1, 0, 1, 0, 1, 0],
#        [0, 1, 0, 1, 0, 1, 0, 1],
#        [1, 0, 1, 0, 1, 0, 1, 0]])
import numpy as np
q9 = np.zeros((8,8))
# 본인 방법
q9_1 = np.argsort(q9)
q9_1[[2*i+1 for i in range(4)],:] +=1
ans9 = q9_1 % 2
print(ans9)
print("="*50)
# 강사 방법
q9_2 = q9.copy()
q9_2[1::2,::2]=1
q9_2[::2,1::2]=1
print(q9_2)
print("="*50+"강사")
# 배열 생성
sum_i_j = np.array([[i + j for j in range(8)] for i in range(8)])
ans9_2 = sum_i_j % 2
print(ans9_2)
print("="*50)
# 타일 함수
pattern = np.array([[0, 1], [1, 0]])
result = np.tile(pattern, (4, 4))
print(result)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
==================================================
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
==================================================강사
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
==================================================
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]